### PR TITLE
Add an entry in the FAQ about the access to formik context

### PR DESCRIPTION
**Pull request by michelts**

### CODE REVIEW

**Comment by michelts** [comment]
@zaguiini I didn't mention useFormikContext because it is not available in the stable formik's realese, do you agree with that?

**Comment by zaguiini** [comment]
You can include the `useFormikContext` with a warning that it's only available on Formik's `v2`

**Comment by michelts** [comment]
Done ;)

Thank you!

**Comment by zaguiini** [comment]
Amazing. Nice one!

**Pull request merged**
